### PR TITLE
Add basic file reader

### PR DESCRIPTION
**Pull request by CorruptX7**
This is just the basic file reader using a hardcoded file path. I will looking into unix redirection as suggested by Ross.

### CODE REVIEW

**Comment by CorruptX7** [comment]
Screenshot 2022-11-08 at 20 44 19

Attached input redirection test via terminal

**Comment by CorruptX7** [comment]
Hi guys, I'd like feedback on my test code please. I may have done something incorrectly because when I run the test it's showing "0/0 tests passed" which shouldn't be the case (Image below).

Screenshot 2022-11-12 at 00 18 41

**Comment by ross39** [comment]
can you show us the unit test?

**Comment by ross39** [comment]
I can help you in person on monday if that suits? not sure why the tests are not running

**Comment by ross39** [comment]
when you switch to the testing branch do my unit tests run for you? if not its probably an issue with your local dev environment

**Comment by CorruptX7** [comment]
> I can help you in person on monday if that suits? not sure why the tests are not running

I may need some help tomorrow

**Comment by CorruptX7** [comment]
> when you switch to the testing branch do my unit tests run for you? if not its probably an issue with your local dev environment

Your testing branch runs just fine for me. I'm not sure why my test is not working on my clientcode branch.

**Comment by CorruptX7** [comment]
> can you show us the unit test?

The test may be incorrect. Please let me know what you think of it. 

Screenshot 2022-11-13 at 14 00 32

**Comment by ross39** [comment]
> > I can help you in person on monday if that suits? not sure why the tests are not running
> 
> I may need some help tomorrow

Yeah that may be best as i am not sure why it is not working. I will have a proper look but something does look off with the unit test. It should at the very least be failing but something is clearly wrong if the test is not even running

**Comment by sunruyun2** [comment]
read file

**Comment by Meiqi-Huang-MCS** [comment]
just check the clientcode branch again. I have helped fixed the bug.

**Review by Meiqi-Huang-MCS — APPROVED** [review]

**Comment by Meiqi-Huang-MCS** [comment]
approve the first version

**Pull request merged**
