### PR TITLE
Add test to test multiple lines of requests

### PR DESCRIPTION
**Pull request by CorruptX7**

### CODE REVIEW

**Comment by CorruptX7** [comment]
There seems to be a conflict :/

**Comment by ross39** [comment]
I will try and fix the merge conflicts 
you might have to do a git rebase

**Comment by CorruptX7** [comment]
> I will try and fix the merge conflicts
> you might have to do a git rebase

Got it!

**Review by Meiqi-Huang-MCS — APPROVED** [review]

**Comment by Meiqi-Huang-MCS** [comment]
restart a new pull request based on the latest main branch.

**Pull request closed without merging**
