### PR TITLE
Transmit Tool and Transmit Tool Testing

### PR DESCRIPTION
**Pull request by hikari-ie**

### CODE REVIEW

**Comment by Meiqi-Huang-MCS** [comment]
截屏2022-11-16 23 24 54

**Comment by Meiqi-Huang-MCS** [comment]
you don't need to add encryption feature on transmit tool. It's not suitable for the very first version. 
plus the external jar you used can not be find in project. I recommend you comment out the encryption code and just test the very basic function.

**Comment by hikari-ie** [comment]
JWT not a module to encrypt the content transmitted between the user and the server, it only use to verify that the request was made by the specified user. In addition, it is placed after LoadBalancer to avoid extra response time.

Thus, I decided to leave it.

If you apply Gradle on your project, it will easy to add dependency for JWT. refer: https://mvnrepository.com/artifact/com.auth0/java-jwt/4.2.1

**Review by ross39 — CHANGES_REQUESTED** [review]
can we get rid of the encryption stuff? Once it is removed I am happy to merge but as it stands right now it will create issues as the project is not setup for encryption and we did agree to add encryption

**Pull request closed without merging**
